### ISSUE TITLE
Observer is unstable on Max 6.1

### ISSUE THREAD

**Issue by shibco** [alpacaaa/max4node#1]
Although Max 6.1 isn't really supported, I'm raising this as a ticket to help out anyone who runs into this issue in the future.

Although max.observe will work for the first few minutes of use, Max 6.1 appears to stop sending messages to max4node, resulting in this error in max4node:

```
_this.emitters[obj.callback].emit('value', obj.value);

TypeError: Cannot call method 'emit' of undefined
at Socket.<anonymous> (node_modules/max4node/max4node.js:41:42)
at Socket.emit (events.js:98:17)
at UDP.onMessage (dgram.js:441:8)
```

Rebooting Live will work for a few more minutes.

**Comment by alpacaaa** [comment]
That's good to know, I haven't had the chance to test this with Max 6.1

On a side note, if you come up with cool stuff using this module, feel free to drop me an email :)

**Comment by shibco** [comment]
It turns out this affects Max 7, also.

**Comment by shibco** [comment]
For more clarity, there is an issue in Max when communicating with LOM that results in LOM returning junk responses.

I've seen this before when using MaxMSP to collect information from LOM and broadcast over UDP. In that particular case, Max wastes significant resources handling the errors, sometimes locking up entirely. This is true for both 6.1 and 7.

**Comment by alpacaaa** [comment]
Do you have some code to reproduce the error? I have been using this module for hours without hiccups and the error you're reporting came up only when I restarted the node script but didn't restart Live, which caused Max to send messages for unhandled events.

That should be easy to fix but looks like your issue is different.

**Comment by shibco** [comment]
I've been using this for a few months and it appears fixed!

**Comment by alpacaaa** [comment]
That's awesome!
