### ISSUE TITLE
track not firing in Ableton project

### ISSUE THREAD

**Issue by EMCP** [alpacaaa/max4node#5]
I am aware this might just be me not knowing what I am doing... 

I am attempting to control ableton via your nodejs package, and want to just fire a clip, but nothing is happening.

I also need to figure out how to let the audio go through the live device generated by this package... so I can still hear the audio.. because I noticed I hear nothing when device is activated in Ableton Live 10.

Any help is greatly appreciated, here's my code and it's output.

```
var Max4Node = require('max4node');

var max = new Max4Node();
max.bind();
console.log("bind returned")

max.call({
    path: 'live_set tracks 0 clip_slots 1 clip',
    method: 'fire'
});

max.count({
    path: 'live_set tracks 0',
    property: 'clip_slots'
}).once('value', function(count) {
    console.log(count + ' clips');
});

console.log("Done.")
```

Getting this console output

```
% node test_max_connect.js
bind returned
Done.
9 clips
```

9 clips IS the correct number.. so that is good.. but now I just need to figure out more of why the audio is not playing..

no sound is played, nor can I see my levels going up as if audio were being produced..

**Comment by EMCP** [comment]
strangely, everything suddenly started working ... my guess is the Ableton project needed to be in a certain state, or the UDP streams weren't getting sent ... hard to know at this stage since I've only just started using this package.. but it looks like now I just need to figure out how to re-route the audio BACK into live.. and will take inspiration from one of their sample devices.

![image](https://user-images.githubusercontent.com/3691722/76160770-4955be00-612d-11ea-8eee-37138a1bdc6c.png)

**Comment by EMCP** [comment]
okay, it seems I need  to reopen this issue... as it indeed does not consistently fire 

even when the device is active I cannot seem to consistently get it to work in Ableton Live 10... might need some pointers on how to debug this... now the output just reacts as if nothing is on..

![image](https://user-images.githubusercontent.com/3691722/76161237-a05d9200-6131-11ea-863b-98c926b4aee7.png)


Perhaps I need help to get the Audio output sending to my speakers like other plugins (see cited max 4 live device earlier in this thread)

**Comment by EMCP** [comment]
I noticed this is a little bit old of a package... could it be I need to update it to use the style of the latest recipes in Max ? 

https://github.com/Cycling74/n4m-examples/blob/master/sockets/max_sockets.js#L16

**Comment by alpacaaa** [comment]
Hey! This package is indeed _very_ old, I'm not even sure if it still works. :(

**Comment by EMCP** [comment]
I actually JUST realized that JS and NodeJS functionality in max are slightly different... I will continue playing with your plugin, but it is very finniky in M4L... but maybe that's enough!

I now have a Node package that in theory can use the nodejs debugger in Max, to make the connection more solid... then wrap the LiveAPI part somehow like you've done

![image](https://user-images.githubusercontent.com/3691722/76246544-34b51b00-623e-11ea-9706-b52bfbfd2988.png)

**Comment by EMCP** [comment]
btw, i got around the sound output issue by just placing the device in an empty track area
